### ISSUE TITLE
When polling (at least?) sometimes gets stuck indefinitely

### ISSUE THREAD

**Issue by lyricnz** [mkj/tgiistat#13]
When I leave tgiistat running in --poll mode (that's how I've noticed it, at least - but looks like it could happen otherwise too), it often "gets stuck" and doesn't query for stats. 

One example below - I hit ^C after noticing it hadn't recorded any stats for ~5 days

```
(venv) Simons-iMac:tgiistat simonroberts$ ./tgiistat.py --csv --poll 30 >> stats.csv
11/08/2018 12:29:54 PM HTTPConnectionPool(host='10.1.1.1', port=80): Max retries exceeded with url: /login.lp?action=getcsrf (Caused by NewConnectionError('<urllib3.connection.HT
TPConnection object at 0x1100ee0f0>: Failed to establish a new connection: [Errno 50] Network is down'))
^CTraceback (most recent call last):
  File "./tgiistat.py", line 294, in <module>
    main()
  File "./tgiistat.py", line 283, in main
    fetch_and_output(config, args.parse, args.gwparse, args.json, args.csv, csv_headers)
  File "./tgiistat.py", line 238, in fetch_and_output
    stats_page, gateway_page = f.get()
  File "./tgiistat.py", line 121, in get
    r = self.session.get(modem_url)
  File "/Users/simonroberts/src/github/tgiistat/venv/lib/python3.7/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/Users/simonroberts/src/github/tgiistat/venv/lib/python3.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/simonroberts/src/github/tgiistat/venv/lib/python3.7/site-packages/requests/sessions.py", line 658, in send
    r.content
  File "/Users/simonroberts/src/github/tgiistat/venv/lib/python3.7/site-packages/requests/models.py", line 823, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/Users/simonroberts/src/github/tgiistat/venv/lib/python3.7/site-packages/requests/models.py", line 745, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/Users/simonroberts/src/github/tgiistat/venv/lib/python3.7/site-packages/urllib3/response.py", line 432, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/Users/simonroberts/src/github/tgiistat/venv/lib/python3.7/site-packages/urllib3/response.py", line 598, in read_chunked
    self._update_chunk_length()
  File "/Users/simonroberts/src/github/tgiistat/venv/lib/python3.7/site-packages/urllib3/response.py", line 540, in _update_chunk_length
    line = self._fp.fp.readline()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt
```

The last stats recorded were:

```
venv) Simons-iMac:tgiistat simonroberts$ tail stats.csv
2018-08-11 12:25:15.299289,930,7950,900,9070,19.2,12.2,5.2,7.1,119.67,1466.42,29.5,48.0,382979,Interleaved,ADSL2+,Up,Technicolor,MediaAccess TGiiNet-1,15.4,15.53.8141-V1-9-0-CRF775,VANT-5,CP1536RA3UF,C4:EA:1D:57:E5:56,1464743
2018-08-11 12:25:48.722095,930,7950,900,9050,19.2,12.2,5.3,7.1,119.73,1466.5,29.5,48.0,383013,Interleaved,ADSL2+,Up,Technicolor,MediaAccess TGiiNet-1,15.4,15.53.8141-V1-9-0-CRF775,VANT-5,CP1536RA3UF,C4:EA:1D:57:E5:56,1464777
2018-08-11 12:27:09.889308,930,7950,900,9070,19.2,12.2,5.2,7.1,119.93,1466.77,29.5,48.0,383093,Interleaved,ADSL2+,Up,Technicolor,MediaAccess TGiiNet-1,15.4,15.53.8141-V1-9-0-CRF775,VANT-5,CP1536RA3UF,C4:EA:1D:57:E5:56,1464858
2018-08-11 12:30:27.980399,930,7950,900,9100,19.2,12.2,5.2,7.2,120.27,1467.58,29.5,48.0,383291,Interleaved,ADSL2+,Up,Technicolor,MediaAccess TGiiNet-1,15.4,15.53.8141-V1-9-0-CRF775,VANT-5,CP1536RA3UF,C4:EA:1D:57:E5:56,1465056
2018-08-11 12:31:47.558926,930,7950,900,9080,19.2,12.2,5.3,7.2,120.48,1468.2,29.5,48.0,383371,Interleaved,ADSL2+,Up,Technicolor,MediaAccess TGiiNet-1,15.4,15.53.8141-V1-9-0-CRF775,VANT-5,CP1536RA3UF,C4:EA:1D:57:E5:56,1465136
2018-08-11 12:32:20.733508,930,7950,900,9080,19.2,12.2,5.3,7.2,120.54,1468.29,29.5,48.0,383399,Interleaved,ADSL2+,Up,Technicolor,MediaAccess TGiiNet-1,15.4,15.53.8141-V1-9-0-CRF775,VANT-5,CP1536RA3UF,C4:EA:1D:57:E5:56,1465169
2018-08-11 12:36:36.273129,930,7950,900,9080,19.2,12.2,5.2,7.2,121.32,1469.76,29.5,48.0,383659,Interleaved,ADSL2+,Up,Technicolor,MediaAccess TGiiNet-1,15.4,15.53.8141-V1-9-0-CRF775,VANT-5,CP1536RA3UF,C4:EA:1D:57:E5:56,1465424
2018-08-11 12:37:47.572944,930,7950,900,9080,19.2,12.2,5.2,7.2,121.42,1469.9,29.5,48.0,383731,Interleaved,ADSL2+,Up,Technicolor,MediaAccess TGiiNet-1,15.4,15.53.8141-V1-9-0-CRF775,VANT-5,CP1536RA3UF,C4:EA:1D:57:E5:56,1465496
2018-08-11 12:38:21.366881,930,7950,900,9080,19.2,12.2,5.3,7.2,121.63,1471.17,29.5,48.0,383765,Interleaved,ADSL2+,Up,Technicolor,MediaAccess TGiiNet-1,15.4,15.53.8141-V1-9-0-CRF775,VANT-5,CP1536RA3UF,C4:EA:1D:57:E5:56,1465529
2018-08-11 12:42:46.881603,930,7950,900,9090,19.2,12.2,5.2,7.1,122.14,1474.03,29.5,48.0,384031,Interleaved,ADSL2+,Up,Technicolor,MediaAccess TGiiNet-1,15.4,15.53.8141-V1-9-0-CRF775,VANT-5,CP1536RA3UF,C4:EA:1D:57:E5:56,1465795
```

**Comment by lyricnz** [comment]
Suggest the HTTP method needs a timeout. http://docs.python-requests.org/en/latest/api/#requests.request

**Comment by lyricnz** [comment]
Committed 8012b28737e1a75ab052734c504cb27e0d95a6f8
