### ISSUE TITLE
Error emitted during query

### ISSUE THREAD

**Issue by lyricnz** [mkj/tgiistat#4]
raceback (most recent call last):
  File "tgiistat.py", line 235, in <module>
    main()
  File "tgiistat.py", line 221, in main
    stats_page = f.fetch()
  File "tgiistat.py", line 117, in fetch
    self.session = self.connect()
  File "tgiistat.py", line 58, in connect
    raise Exception("Bad csrf response")
Exception: Bad csrf response

**Comment by lyricnz** [comment]
Likely because of:
```
/Users/simonroberts/src/github/tgiistat/venv/bin/python /Users/simonroberts/src/github/tgiistat/tgiistat.py -d --csv
27/07/2018 01:55:24 PM Starting new HTTP connection (1): 10.1.1.1
27/07/2018 01:55:24 PM http://10.1.1.1:80 "GET /login.lp?action=getcsrf HTTP/1.1" 503 212
27/07/2018 01:55:24 PM csrf <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body bgcolor="white">
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx/1.4.7</center>
</body>
</html>

Traceback (most recent call last):
  File "/Users/simonroberts/src/github/tgiistat/tgiistat.py", line 235, in <module>
    main()
  File "/Users/simonroberts/src/github/tgiistat/tgiistat.py", line 221, in main
    stats_page = f.fetch()
  File "/Users/simonroberts/src/github/tgiistat/tgiistat.py", line 117, in fetch
    self.session = self.connect()
  File "/Users/simonroberts/src/github/tgiistat/tgiistat.py", line 58, in connect
    raise Exception("Bad csrf response")
Exception: Bad csrf response

Process finished with exit code 1
```

**Comment by lyricnz** [comment]
Are there some documents about "GET /login.lp?action=getcsrf HTTP/1.1" ?
It looks like it's a bit unreliable (on my modem at least??). Maybe DoS prevention?

**Comment by mkj** [comment]
Aha. I guess tgiistat should print a sensible message when it gets a 503 error code
