### ISSUE TITLE
Error emitted during query: IndexError: list index out of range

### ISSUE THREAD

**Issue by lyricnz** [mkj/tgiistat#5]
Traceback (most recent call last):
  File "tgiistat.py", line 235, in <module>
    main()
  File "tgiistat.py", line 224, in main
    stats = parse(stats_page)
  File "tgiistat.py", line 171, in parse
    res['up_rate'], res['down_rate'] = fetch_pair("Line Rate", 'Mbps')
  File "tgiistat.py", line 144, in fetch_pair
    updown = lr[0].parent.parent.find_all(string=re.compile(unit))
IndexError: list index out of range

**Comment by lyricnz** [comment]
Between this and #4 there's quite a few failures during repeated polling. Following is output from '--csv' with 30 second gap between, with date emitted too.  Lots of gaps.

```
Fri 27 Jul 2018 12:59:50 AEST,740,7780,710,7880,19.2,12.4,4.9,5.5,804.14,2042.33,29.7,48.0,2469,Interleaved,ADSL2+,Up
Fri 27 Jul 2018 13:00:54 AEST,
Fri 27 Jul 2018 13:01:55 AEST,
Fri 27 Jul 2018 13:02:55 AEST,
Fri 27 Jul 2018 13:03:55 AEST,
Fri 27 Jul 2018 13:04:55 AEST,
Fri 27 Jul 2018 13:05:56 AEST,
Fri 27 Jul 2018 13:06:56 AEST,740,7780,710,7900,19.2,12.4,4.7,5.6,804.78,2043.91,29.7,48.0,2895,Interleaved,ADSL2+,Up
Fri 27 Jul 2018 13:07:59 AEST,740,7780,710,7860,19.2,12.4,4.8,5.5,804.97,2044.68,29.7,48.0,2957,Interleaved,ADSL2+,Up
Fri 27 Jul 2018 13:09:02 AEST,740,7780,710,7910,19.2,12.4,4.8,5.6,805.04,2044.73,29.7,48.0,3021,Interleaved,ADSL2+,Up
Fri 27 Jul 2018 13:10:06 AEST,740,7780,720,7880,19.2,12.4,5.2,5.6,805.2,2044.91,29.7,48.0,3083,Interleaved,ADSL2+,Up
Fri 27 Jul 2018 13:11:09 AEST,740,7780,730,7830,19.2,12.4,5.4,5.4,805.31,2045.23,29.7,48.0,3147,Interleaved,ADSL2+,Up
Fri 27 Jul 2018 13:12:13 AEST,740,7780,710,7870,19.2,12.4,5.0,5.5,805.38,2045.38,29.7,48.0,3211,Interleaved,ADSL2+,Up
Fri 27 Jul 2018 13:13:16 AEST,740,7780,710,7760,19.2,12.4,4.9,5.2,805.56,2045.57,29.7,48.0,3275,Interleaved,ADSL2+,Up
Fri 27 Jul 2018 13:14:19 AEST,740,7780,710,7860,19.2,12.4,4.8,5.6,805.62,2045.64,29.7,48.0,3337,Interleaved,ADSL2+,Up
Fri 27 Jul 2018 13:15:23 AEST,740,7780,710,7900,19.2,12.4,4.8,5.6,805.74,2045.79,29.7,48.0,3401,Interleaved,ADSL2+,Up
Fri 27 Jul 2018 13:16:26 AEST,740,7780,710,7810,19.2,12.4,4.8,5.4,805.85,2045.94,29.7,48.0,3465,Interleaved,ADSL2+,Up
Fri 27 Jul 2018 13:17:29 AEST,740,7780,710,7880,19.2,12.4,4.9,5.6,805.94,2046.06,29.7,48.0,3527,Interleaved,ADSL2+,Up
Fri 27 Jul 2018 13:18:33 AEST,740,7780,720,7890,19.2,12.4,5.0,5.6,806.12,2046.82,29.7,48.0,3591,Interleaved,ADSL2+,Up
Fri 27 Jul 2018 13:19:36 AEST,
Fri 27 Jul 2018 13:20:40 AEST,
Fri 27 Jul 2018 13:21:44 AEST,
Fri 27 Jul 2018 13:22:47 AEST,
Fri 27 Jul 2018 13:23:50 AEST,640,7130,640,7540,19.2,12.4,6.5,6.4,806.29,2046.94,29.7,48.0,23,Interleaved,ADSL2+,Up
Fri 27 Jul 2018 13:24:54 AEST,640,7130,630,7520,19.2,12.4,6.7,6.4,807.5,2048.91,29.7,48.0,87,Interleaved,ADSL2+,Up
Fri 27 Jul 2018 13:25:57 AEST,640,7130,630,7560,19.2,12.4,6.8,6.5,808.57,2052.02,29.7,48.0,149,Interleaved,ADSL2+,Up
Fri 27 Jul 2018 13:27:01 AEST,640,7130,640,7580,19.2,12.4,6.7,6.6,809.18,2055.49,29.7,48.0,215,Interleaved,ADSL2+,Up
Fri 27 Jul 2018 13:28:05 AEST,640,7130,640,7590,19.2,12.4,6.8,6.6,809.29,2055.63,29.7,48.0,277,Interleaved,ADSL2+,Up
Fri 27 Jul 2018 13:29:08 AEST,640,7130,640,7580,19.2,12.4,6.9,6.5,809.4,2055.77,29.7,48.0,341,Interleaved,ADSL2+,Up
Fri 27 Jul 2018 13:30:11 AEST,640,7130,640,7550,19.2,12.4,7.0,6.6,809.47,2055.85,29.7,48.0,405,Interleaved,ADSL2+,Up
Fri 27 Jul 2018 13:31:15 AEST,640,7130,650,7590,19.2,12.4,7.4,6.6,809.55,2055.94,29.7,48.0,467,Interleaved,ADSL2+,Up
Fri 27 Jul 2018 13:32:18 AEST,640,7130,640,7590,19.2,12.4,7.2,6.6,809.62,2056.04,29.7,48.0,531,Interleaved,ADSL2+,Up
Fri 27 Jul 2018 13:33:22 AEST,
Fri 27 Jul 2018 13:34:22 AEST,
Fri 27 Jul 2018 13:35:22 AEST,
Fri 27 Jul 2018 13:36:22 AEST,
Fri 27 Jul 2018 13:37:22 AEST,640,7130,640,7640,19.2,12.4,6.9,6.7,809.89,2056.39,29.7,48.0,835,Interleaved,ADSL2+,Up
Fri 27 Jul 2018 13:38:26 AEST,640,7130,640,7620,19.2,12.4,7.0,6.6,809.93,2056.43,29.7,48.0,899,Interleaved,ADSL2+,Up
Fri 27 Jul 2018 13:39:29 AEST,640,7130,640,7640,19.2,12.4,7.1,6.7,810.04,2056.79,29.7,48.0,963,Interleaved,ADSL2+,Up
```

**Comment by lyricnz** [comment]
I'm going to close this one - unable to reproduce. Probably caused by failure to query the modem, and badly handled exception?
